### ISSUE TITLE
webhook is not pulling from osticket

### ISSUE THREAD

**Issue by time2mac** [clonemeagain/osticket-slack#10]
I'm pretty sure I've done something completely wrong, but when I pasted the webhook in the config as below:
'slack-webhook-url'          => new TextboxField(array(
                'label'         => $__('https://hooks.slack.com/services/xxxxx'),

I'm getting the plugin showing as installed and enabled in osticket, but it's not pulling to slack.
I've checked the webhook, channel authorisation etc. but that all seems fine.

Any idea what I'm doing wrong?

**Comment by clonemeagain** [comment]
Hi, 

You shouldn't have to modify the source, after you've installed the plugin files, simply use the admin console to configure the plugin with your hook url. Then enable the plugin.

**Comment by time2mac** [comment]
oh, I misunderstood the instructions. When it said to paste into the config, I thought it meant into the config.php rather than into the osticket plugin settings page.

That could be clarified a little better on the readme.
Thanks for the help!
