### ISSUE TITLE
Postfix config.

### ISSUE THREAD

**Issue by Youdam09** [clonemeagain/osticket-slack#12]
Hello, can you say me which the best postfix configuration to connect the API ??
I have a internal mail server with Debian using the 25 port for smtp.
can´t connect with slack.

**Comment by clonemeagain** [comment]
Hi, this plugin is a bridge between a web based ticket system and slack, it doesn't use email itself.

If you're trying to configure osticket to use pipes for email, there is a config described in the wiki: http://osticket.com/wiki/Email_Piping I've not tried it myself.

In saying that, I'm sure there is a way, postfix seems pretty flexible. Couple a config like this https://unix.stackexchange.com/questions/178396/run-script-on-receipt-of-email with a shell script like this https://github.com/course-hero/slacktee and it should work.

**Comment by clonemeagain** [comment]
Assuming resolved.
