### ISSUE TITLE
Error 500 when creating a ticket

### ISSUE THREAD

**Issue by kwackerz** [clonemeagain/osticket-slack#14]
Hi,

When the plugin is enabled, Creating a ticket ends up with a http error 500 error. any ideas? its a fairly generic error code. when i disable the plugin and tickets create fine

Thanks,

**Comment by clonemeagain** [comment]
What version of osticket, PHP, curl etc are you using?

**Comment by clonemeagain** [comment]
I checked it, and I've used php 5.6 syntax, so if you're using an earlier version (:-( you'll need to upgrade.

http://php.net/supported-versions.php

Hmm, definitely.

**Comment by kwackerz** [comment]
ah, it wasn't php. im on 7.0.30  but... it was php_curl. updated that and it sprang to life!

thanks for the pointer though :-)
