### ISSUE TITLE
Include unofficial Discord support

### ISSUE THREAD

**Issue by MagiskSec** [clonemeagain/osticket-slack#17]
Hi there,

It would be really cool to mention that this already supports Discord in the readme - I'd submit a wiki page with instructions if you want.. Discord has a "slack-compatible" webhook in it's API - so you can very easily turn this into a Discord notifier too.

Cheers,
Magic.

**Comment by clonemeagain** [comment]
Hey chief, haven't used Discord much, PR for the README would work fine mate, cheers! (no wiki pages yet)

Looks like it here: https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook

**Comment by MagiskSec** [comment]
PR'd the Readme.

Thanks for the script, it's been a lifesaver and works wonders for our use-case.
