### ISSUE TITLE
Plugin dont send messages

### ISSUE THREAD

**Issue by Rodrigocg** [clonemeagain/osticket-slack#2]
Good evening!

I have installed this plugin, but its not send msgs for the #slack using my webhook.

Using the Postman, the message is send.

I used version 1.10

Help me please. :D

**Comment by clonemeagain** [comment]
Hey chief. Which "Postman" are you referring to? 

Have you got any logs? Error messages? Bit hard to know what's gone wrong with nothing to go on. 

I assume you have a slack channel, and have successfully created the webhook for the channel, and have pasted that hook into the config, then created a ticket as a user, or replied to one as a user..

**Comment by perryk** [comment]
Something else to verify which always catches me out is that the plugin is actually enabled too.

**Comment by clonemeagain** [comment]
Ooh, good point. Just because it's installed and configured, doesn't mean it's enabled!

**Comment by Rodrigocg** [comment]
The plugin was disabled. Sorry (I'm new user).

Thanks for help.

**Comment by clonemeagain** [comment]
All good mate, any feedback you have is appreciated too.
