### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by vzan2012** [clonemeagain/osticket-slack#21]
Hi,
I installed the plugin as described and created a slack app.
I'm experiencing the problem that the osTicket (1.10) doesn't send any notifications and logs are not generated.
I have also checked the php-curl, but the php curl is working and the plugin also turned on.
How to debug it?
Pls provide the solutions for it

**Comment by clonemeagain** [comment]
It's installed, enabled, configured and has the prerequisites? Hard to debug then mate if it's not logging, try deleting it and start again

**Comment by vzan2012** [comment]
Thank you, I followed the steps as you said... It is working now.
