### ISSUE TITLE
get errormail for every new ticket

### ISSUE THREAD

**Issue by d3datadev** [clonemeagain/osticket-slack#22]
Basically the connection to slack works. But now I get a mail with every new ticket:

----------------------------------
Subject: "CronJob /path/to/osticket/mail_cron.sh"
message: "didn't trigger"
----------------------------------

what could be the reason? How can I fix it?
this mail starts after activating the plugin.

Thomas

**Comment by clonemeagain** [comment]
Haven't looked at it in a while, but if you've got the error message, and
any matching server logs we might be able to help.

**Comment by d3datadev** [comment]
thanks for your response.
Unfortunality I have no new lines in our apache error.log.

Is there anything else I can check?

**Comment by argumemnon** [comment]
I am also having this issue. 
The email I receive has the subject line
Cron <root@server> /usr/bin/php /path/to/osticket/api/cron.php

with the body message "didn't trigger"

In my apache error log for osTicket (in osticket/log/error.log) I saw
`[php7:notice] [pid 25329 (<--apache)] [client myremoteipaddress:51536] didn't trigger , referer: https://osticketaddress.com/scp/tickets.php?a=open&uid=69`

**Comment by argumemnon** [comment]
Further research shows that it is being triggered by [slack.php](https://github.com/clonemeagain/osticket-slack/blob/235436a8fb92168f01fa4d4e55336d203c6eded4/slack.php#L139):

[140       error_log("$ticket_subject didn't trigger $regex_subject_ignore");](https://github.com/clonemeagain/osticket-slack/blob/235436a8fb92168f01fa4d4e55336d203c6eded4/slack.php#L139)

**Comment by clonemeagain** [comment]
I can remove that line.. done

https://github.com/clonemeagain/osticket-slack/commit/1365d59683ae1a8a0dc3450f5c1c9dd70d406624
