### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by Findarato** [clonemeagain/osticket-slack#4]
When links to the tickets are posted in slack they show up with a missing / 

an example 
`
https://website.comscp/tickets.php?id=884`

**Comment by clonemeagain** [comment]
Odd, I thought I fixed that in bbbd444fcb5f8e850e4fb8fa4ae4c5479305e8be

Have you got the latest version?

**Comment by clonemeagain** [comment]
Assuming resolved.
