### ISSUE TITLE
Receiving e-mail error

### ISSUE THREAD

**Issue by dotcade** [clonemeagain/osticket-slack#5]
Every time a ticket is submitted I get an error message with the subject "Slack posting issue!" and the body includes a link to https://hooks.slack.com/services/XXXXXXX/XXXXXXXXXXXXXX/XXXXXXXXXXXX with the text - SSL certificate problem: unable to get local issuer certificate.

Any idea what could be causing?

**Comment by clonemeagain** [comment]
I suspect a TLS version error, like https://stackoverflow.com/questions/35131590/php-curl-set-ssl-version

Perhaps your version of php_curl is old? What version are you running? What's your openssl situation?

**Comment by clonemeagain** [comment]
Nothing heard.
