### ISSUE TITLE
not working....

### ISSUE THREAD

**Issue by snizzleorg** [clonemeagain/osticket-slack#8]
I installed the plugin as described and created a slack app. Checked that it is working by issuing  a notification via curl. However osTicket (1.10) never sends any notifications. The logs are empty any idea?

**Comment by clonemeagain** [comment]
Check that the plugin itself is turned on. After it's installed it must
then be enabled.

**Comment by snizzleorg** [comment]
Thanks. It was enabled but php-curl was missing. Its working now! Thanks!

**Comment by vzan2012** [comment]
Hi, 
I'm also experiencing the same problem. The osTicket (1.10) doesn't send any notifications and logs are not generated. 
I have also checked the php-curl, but the php curl is working and the plugin also turned on.
How to debug it? 
Pls provide the solutions for it
